const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO'
const EDIT_TODO = 'EDIT_TODO'
const COMPLETE_TODO = 'COMPLETE_TODO'
const COMPLETE_ALL = 'COMPLETE_ALL'
const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
const INIT_TODOS = 'INIT_TODOS'
const UPDATE_TODOS = 'UPDATE_TODOS'

export {
    ADD_TODO,
    DELETE_TODO,
    EDIT_TODO,
    COMPLETE_TODO,
    COMPLETE_ALL,
    CLEAR_COMPLETED,
    INIT_TODOS,
    UPDATE_TODOS,
}
